### ISSUE TITLE
How to use socks5 proxy

### ISSUE THREAD

**Issue by Paushyon** [guibacellar/TEx#24]
Errors:
raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)
In telegram_connection_manager.py, I add a proxy, 
proxy = (socks.SOCKS5, 'IP address',  port, username, password)
client = TelegramClient(
                os.path.join(session_dir, config['CONFIGURATION']['phone_number']),
                data['telegram_connection']['api_id'],
                data['telegram_connection']['api_hash'],
                catch_up=True,
                device_model='TeX',
                proxy=proxy
                )
but it does not work, what should I do to make it available？

**Comment by guibacellar** [comment]
Hi @Paushyon 

Sorry for the tool do not have this feature Yet.

Please, check the documentation at: https://docs.telethon.dev/en/stable/basic/signing-in.html

Also, I create 2 new issues for this features:
https://github.com/guibacellar/TEx/issues/26
https://github.com/guibacellar/TEx/issues/27

**Comment by Paushyon** [comment]
Thanks! Following the Telethon docs, it worked well.

**Comment by guibacellar** [comment]
Greate
Can you, please, share the code? I'm working on a "Official Telegram Explorer" version :D
