### ISSUE TITLE
Quality of Life request (not issue)

### ISSUE THREAD

**Issue by sojubear** [guibacellar/TEx#47]
Good day, I love your telegram scrapper. its been very beneficial for my use cases! May I request these few updates if you have the time ?

1. A keep alive ping sent to a discord webhook every x minutes so we know that the bot is still running

For example : 
[keep-alive]
interval=300
notifier=NOTIFIER.DISCORD.MY_HOOK_1

2. A way to put every search term into a single finder rule and notifier, because now its one rule for one notifier, something like this : 

For example : 
[FINDER.RULE.MessagesWithURL]
type=regex
regex1=aaa
regex2=bbb
regex3 =ccc 
notifier=NOTIFIER.DISCORD.MY_HOOK_2

Thank you very much once again I love this app

**Comment by guibacellar** [comment]
Hi @sojubear 

First of all, I'm very happy to know that you are using TEx and they are helping you. Thank's a Lot.

I Love your ideias, really thanks for share.

Particularly the Keep-Alive may be a problem due the fact about how I use the Asyncio, but, I'm thinking here :)

Anyway, I create 2 new Issues (for Tracking of changes and tests) with you 2 ideas:

- [https://github.com/guibacellar/TEx/issues/48](https://github.com/guibacellar/TEx/issues/48)
- [https://github.com/guibacellar/TEx/issues/49](https://github.com/guibacellar/TEx/issues/49)


I can't promise the KeepAlive for the next release (0.3.0) but the RegEx ideia I can ;)

I'm closing this issue and feel free to follow the new two and comment there.

Again, Thanks a Lot
