### ISSUE TITLE
[Feature Request] Multiple features

### ISSUE THREAD

**Issue by 0xEnders** [guibacellar/TEx#56]
Hi again! Thank you for the quick updates and implementation of features. I have tested the V0.3.0-dev build and everything works perfectly!

 I have a few more QOL requests if you you think its useful 

1. Translation :
Will it be possible to add a translation function to the listener? Understand that it might be slow if you pipe from telegram > translator > discord so it could be optional. Could be like how you made it for OCR, e.g
[TRANSLATION]
enabled=true

message 
===TRANSLATION===
translated message 

2. Cut db file every day  :

I am not sure if this is possible, but could there be an option to cut the .db file every day so we can run our own scripts to export or mail it somewhere else? for example something like 
[EXPORT_DB]
enabled=true
time_to_cut_file=0000H GMT+0 

3. config_file for exporting of db to csv  :
An option to export the sqlite3 db to csv with our custom headers. 
For example now the telegram_message csv starts with id, group_id , media_id etc. Is it possible for us to use another config file to choose what to export? E.g, 
#export config file
[EXPORT_CSV]
header=group_id
header=group_username
header=title
header=message 

Thank you once again for your hard work!

**Comment by guibacellar** [comment]
Hi. I'm Happy to know that you are testing the 0.3.0 :D 

About the features:

1-) You tell the translation, translation? Like, ENG to PT_BR or RU to ENG?

2 and 3-) I'm planning a auto export already, probably because the same problem that you are facing. Ref: https://github.com/guibacellar/TEx/issues/53

I'm prioritizing the export feature to 0.3.0 official release.

**Comment by guibacellar** [comment]
And one thing that you say making me think about create a "Beta" build for the working versions. This way, anyone can download and try the On Development versions.

**Comment by guibacellar** [comment]
![image](https://github.com/guibacellar/TEx/assets/19396472/6f16998b-ebd0-4cf6-a986-fbb83fcff343)
It' taking a time, but I'm almost there ;)

Realtime, Rolling file exporting as csv, xml, json or pickle......

**Comment by guibacellar** [comment]
Closing for Issues Cleanup. All requests features was addressed in other issues
