### ISSUE TITLE
install

### ISSUE THREAD

**Issue by sebatrino** [guibacellar/TEx#59]
Can someone help me how to install this on a windows pc? i+ve installed python but i cannot get this package to install. i tried anything i could, through cmd in admin mode, through python module, python 3.10 but i only get some error when i tray to activate the command:

Installing
Telegram Explorer is available through *pip*, so, just use pip install in order to fully install TeX.

```bash
pip install TelegramExplorer
```

<!--

We got scammed by some jerk on telegram and as it seem he's been running his thing for years. this is the only way we can get some data about him to prove this to interpool and other authorities.

Well somehow something got installed once i copied this command from this window and this is what we get:

Successfully built Telethon
Installing collected packages: urllib3, idna, charset-normalizer, certifi, zipp, tomli, requests, msgpack, more-itertools, rapidfuzz, pywin32-ctypes, pyrsistent, pyproject-hooks, ptyprocess, platformdirs, packaging, jaraco.classes, importlib-metadata, filelock, distlib, crashtest, colorama, cachecontrol, attrs, virtualenv, trove-classifiers, tomlkit, shellingham, requests-toolbelt, pyasn1, poetry-core, pkginfo, pexpect, keyring, jsonschema, installer, dulwich, cleo, build, typing-extensions, tgcrypto, rsa, pyproject-api, pyaes, poetry, pluggy, MarkupSafe, greenlet, chardet, cachetools, tox, toml, telethon-cryptg, Telethon, SQLAlchemy, pytz, poetry-plugin-export, Jinja2, discord-webhook, cryptg, aiosqlite, TelegramExplorer
    Running setup.py install for pyaes ... done
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.3 SQLAlchemy-2.0.23 TelegramExplorer-0.2.15 Telethon-1.29.2 aiosqlite-0.19.0 attrs-23.1.0 build-0.10.0 cachecontrol-0.13.1 cachetools-5.3.2 certifi-2023.7.22 chardet-5.2.0 charset-normalizer-3.3.2 cleo-2.1.0 colorama-0.4.6 crashtest-0.4.1 cryptg-0.4.0 discord-webhook-1.3.0 distlib-0.3.7 dulwich-0.21.6 filelock-3.13.1 greenlet-3.0.1 idna-3.4 importlib-metadata-6.8.0 installer-0.7.0 jaraco.classes-3.3.0 jsonschema-4.17.3 keyring-24.3.0 more-itertools-10.1.0 msgpack-1.0.7 packaging-23.2 pexpect-4.8.0 pkginfo-1.9.6 platformdirs-3.11.0 pluggy-1.3.0 poetry-1.6.1 poetry-core-1.7.0 poetry-plugin-export-1.6.0 ptyprocess-0.7.0 pyaes-1.6.1 pyasn1-0.5.0 pyproject-api-1.6.1 pyproject-hooks-1.0.0 pyrsistent-0.20.0 pytz-2023.3.post1 pywin32-ctypes-0.2.2 rapidfuzz-3.5.2 requests-2.31.0 requests-toolbelt-1.0.0 rsa-4.9 shellingham-1.5.4 telethon-cryptg-0.0.4 tgcrypto-1.2.5 toml-0.10.2 tomli-2.0.1 tomlkit-0.12.2 tox-4.11.3 trove-classifiers-2023.11.13 typing-extensions-4.8.0 urllib3-2.1.0 virtualenv-20.24.6 zipp-3.17.0
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\***\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

What do we do from here, how can we use this to search and download all data from this user that scammed us and many many others with the help of his telegram adrress?

**Comment by sebatrino** [comment]
Somehow we got it, i think so, this is what comes at the end of the instalation- 'Successfully built Telethon
Installing collected packages...' How do we use this how do we start it to search for all the data of this scammer who stole money from so many others with the help of his telegram adrress?

**Comment by sebatrino** [comment]
Hi guibacellar/TEx,

thank you for all your effort. I tried following your instructions but to
be honest that is way above my capabilities.
I know, for you as a professional in programming this seems easy, but for
us, elderly people, this is a high tech of the next century.
Is there any way i could forward you the telegram address of this scammer
so you can extract all the data so i can forward them with all the other
data i already collected about him to the authorities?
He i still scamming people, his eth address shows that clearly. He receives
only small amounts as he did from me, there're no big numbers as he brags
in his videos how much he makes with these deployments of his scripts.

I don't expect to get my money back, but youtube and telegram don't give a
shit if one reports a scammer like him, but maybe, if a cyber crime agency
gets on his trail, that could force telegram and youtube to shut down all
his channels for good.
At least he won't be able to scam any more people as he did in the past
years.

Best,
S

**Comment by guibacellar** [comment]
Technically speaking, TEx was designed to be the simplest to use. I understand that your problem is previous, that is, in the installation process from Python to TEx.

I would love to be able to guide you through this process, as I understand that it would be beneficial for you to learn and use other tools that you come across.

And, yes, if you want to chat with me in private, feel free to do so. All my contacts and profiles are available at [https://github.com/guibacellar](https://github.com/guibacellar). If you have a Linkedin account, please, contact-me there.https://github.com/guibacellar

**Comment by sebatrino** [comment]
Hi,

*'I would love to be able to guide you through this process, as I
understand that it would be beneficial for you to learn and use other tools
that you come across.'*

How would that work? I have no idea on which continent you are and there're
multiple hours difference between Europe where i am and who knows where you
are.

Believe it or not i belong to the old OG's, from the time we played with ZX
spectrum, commodore 64 and such, so i had my work done with computer
coding, but after the car accident f'ed up my brains i'm literally near to
go into early pension, unemployable.

I need this data not for my benefits but to help authorities to stop this
scammer, because he is a special kind of species. He is not as greedy as
all the others, he takes his time, is okay with small profits but he does
that from week to week, month to month and the money just keeps coming, it
is not much, but with the time the number only grows larger.

Can you provide me with detailed instructions how can i add this Tex to
python once i have python installed?
I tried it with chat gpt but it simply wouldn't work, i got repeatedly
some, ' cannot find path to...?
For some reason on my old pc cmd and power-shell cannot get a direct access
to specific files/folders.
I had a similar problem with Yubico desktop version, it simply would not
work until i set up a new pc with ryzen 5700g, fresh windows and before i
set up q+q shut up i tried it and yubico worked. I managed to set up yubico
and q+q so that they now both work.

Maybe on this new pc i can also get your Tex working.
I am afraid to discuss any specifics about the person who scammed me,
because he could easily be on github, i mean he is a dev, at least he
claims so and after what i found out this week about one of the most
popular 'passive investment' platforms, god help these people when they
realize whom they gave their money.

best,

**Comment by guibacellar** [comment]
No problem, we can do this one step at time, LOL.

In order to proper help and guide you in the process, I ask you to add me on Linkedin and call me there

**Comment by sebatrino** [comment]
Hi,

i downloaded and installed python 3.10, opened cmd and wanted to start tex,
with no idea how, and end up with this:











*'C:\Windows\system32>pythonPython 3.10.0 (tags/v3.10.0:b494f59, Oct  4
2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32Type "help",
"copyright", "credits" or "license" for more information.>>>
Scripts\pip.exe install TelegramExplorer  File "<stdin>", line 1
Scripts\pip.exe install TelegramExplorer
       ^SyntaxError: unexpected character after line continuation
character>>> Scripts\pip.exe install TelegramExplorer  File "<stdin>", line
1    Scripts\pip.exe install TelegramExplorer*

*                                           ^SyntaxError: unexpected
character after line continuation character*
>>>

What is the basic line/command (without going into the virtualization
thing) to install tex into python which is installed on my C: drive?
Also, i've read that one must have the phone number of a specific telegram
channel (phone_number > Required - Target Phone Number) if one wants to
access and download it?
Would the name of the telegram channel also do, the name with which one
gets the invitation and signs up to that channel?

Which part of python must one use to install tex, the module, the idle, or
python.exe itself?
Would it help if i move the 'tex' folder with its data into some part of
where python is installed on C drive?

I tried this from your link:

*'python -m venv /path/to/new/virtual/environment'*

And got:







*                        ^^^^^^^^^^^^^^^^^^^^^^^^SyntaxError: invalid
syntax. Perhaps you forgot a comma?>>> python -m venv
/path/to/new/virtual/environment  File "<stdin>", line 1    python -m venv
/path/to/new/virtual/environment
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^SyntaxError: invalid syntax.
Perhaps you forgot a comma?>>>*

I tried this in cmd and python itself, same negative result.

then i tried the next option













*c:\>Python35\python -m venv c:\path\to\myenvand again with no luck. i
changed the 35 to 31, maybe that's the right version of python but again no
luck.SyntaxError: invalid syntax. Perhaps you forgot a comma?>>> python -m
venv /path/to/new/virtual/environment  File "<stdin>", line 1    python -m
venv /path/to/new/virtual/environment
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^SyntaxError: invalid syntax.
Perhaps you forgot a comma?>>> c:\>Python35\python -m venv
c:\path\to\myenv  File "<stdin>", line 1    c:\>Python35\python -m venv
c:\path\to\myenv*
                                               ^








*SyntaxError: unexpected character after line continuation character>>>
c:\>Python31\python -m venv c:\path\to\myenv  File "<stdin>", line 1
c:\>Python31\python -m venv c:\path\to\myenv
               ^SyntaxError: unexpected character after line continuation
character>>> c:\>python -m venv  File "<stdin>", line 1    c:\>python -m
venv*
                     ^








*SyntaxError: unexpected character after line continuation character>>>
c:\path\to\myenv  File "<stdin>", line 1    c:\path\to\myenv
   ^SyntaxError: unexpected character after line continuation character>>>
c:\>Python35\python -m venv  File "<stdin>", line 1    c:\>Python35\python
-m venv*
                              ^






*SyntaxError: unexpected character after line continuation character>>>
c:\path\to\myenv  File "<stdin>", line 1    c:\path\to\myenv
   ^SyntaxError: unexpected character after line continuation character>>>*

Best,
S
