### ISSUE TITLE
[Update] My personal testing on EC2 instance with 6000+ search terms 

### ISSUE THREAD

**Issue by 0xEnders** [guibacellar/TEx#61]
I want to share that TEx runs properly on Amazon EC2 free instance. You can sign up and let it run for free(i think) for 12 months. Please check their website for details.

I am using this machine image
![qwer](https://github.com/guibacellar/TEx/assets/82849660/0691a8ed-ae07-43e0-88da-50e227290cc7)

with this specification
![qwer2](https://github.com/guibacellar/TEx/assets/82849660/03ddfa42-e8f4-4ac4-9ff6-d7c318a73cae)

the image does not have native desktop GUI so follow this guide to install it:

https://shrihariharidas73.medium.com/how-to-setup-gui-desktop-with-ubuntu-on-aws-ec2-ea713d836a58

Subsequently you can pip install TEx as normal and run the scraper

However take note that due to the limitations of the EC2 instance specs, it might be difficult for you to transfer files if you intend to do so over their internet browser, but it can be prevented if you RDP and enable shared drives to copy paste your logs over. Alternatively you can do it using secure copy

Also, I am currently running with 5000+ search terms on the same machine. I had some issues with the new config format where you could use multiple regex for a single notifier, so i went back to the old way of using 1 regex for  1 notifier.

Also, have created a python script that helps to convert the wordlist into the configfile 

![Untitled](https://github.com/guibacellar/TEx/assets/82849660/f344d260-9dc3-4107-a5cd-8fe10cd2e058)

Its a very basic script so amend the variables yourself :D

https://github.com/0xEnders/wordlist_to_config/blob/main/wordlist_to_config.py

**Comment by guibacellar** [comment]
Can you please, explain what problem with the new multi regex support are you facing? That allow me to update/fix to better help your work and other users .
