### ISSUE TITLE
Error reporting 

### ISSUE THREAD

**Issue by makar96** [guibacellar/TEx#64]
Hello! When running the command "python3 -m TEx listen --config..." an error appears. Could you help me understand its essence?  
I would be very grateful

![image](https://github.com/guibacellar/TEx/assets/141029780/6f1e7a18-aa6a-496b-9bd4-d20a4f6459bb)

![image](https://github.com/guibacellar/TEx/assets/141029780/19a14414-bceb-43a3-be32-745ff2f7d75d)

**Comment by guibacellar** [comment]
Hi @makar96 

Probably the error happens because you actively interrupt the process using a CTRL+C on your keyboard.

Please, try to start TEx in the same way you already try, but let the code run freely.

**Comment by makar96** [comment]
Thanks for the advice.
If the process is not interrupted, the following error occurs:  
![image](https://github.com/guibacellar/TEx/assets/141029780/1af39ef7-0b2d-4132-9b12-fba08bf9e9d5)

I'm sorry for the trouble
