### ISSUE TITLE
listen messages error

### ISSUE THREAD

**Issue by WhitePhantom99** [guibacellar/TEx#67]
Hi all, when running the command to start "listen messages" the following errors are detected in the figure.
what could be the cause? 
the file configuration was done correctly and the login and group update as well.
thanks for the  support 
![error](https://github.com/guibacellar/TEx/assets/48584658/086c7ef6-2786-43b5-a11e-192dd0ccec82)

**Comment by guibacellar** [comment]
This issue still? Or TEx are working normal?

**Comment by maxpainnogain1** [comment]
This issue gets resolved once you again use the connect command with your config file, i have seen this couple of times
