### ISSUE TITLE
Telegram account has been banned.

### ISSUE THREAD

**Issue by iris-cat-dev** [guibacellar/TEx#70]
I monitor group chat content through this project, but my account is often banned. Have anyone encountered this problem?

**Comment by guibacellar** [comment]
Hi. 

Are you using the "listen" command or using the "download_messages"?

Telegram have they own rules/reasons to ban an account. Ex: IP mismatched with account origin, excessive name resolution (note: TEx don't do that), Virtual Numbers, etc.

**Comment by iris-cat-dev** [comment]
Thank you for your response, I think it may be due to the IP.
